
CREATE TABLE CUSTOMER (
CUSTOMERID VARCHAR2(30) primary key,
CUSTOMERPW VARCHAR2(30),
NAME VARCHAR2(30),
PHONE VARCHAR2(30),
BIRTHDATE VARCHAR2(60) DEFAULT SYSDATE, --원하면 VARCHAR2로 수정가능
ADDRESS VARCHAR2(60),
INDATE DATE DEFAULT SYSDATE 
);

CREATE TABLE PRODUCT(
PRODUCTSEQ NUMBER(6) PRIMARY KEY,
NAME VARCHAR2(30),
QUANTITY NUMBER(6),
PRICE NUMBER(6),
COMMENTS VARCHAR2(100),
INDATE DATE DEFAULT SYSDATE
);

CREATE TABLE SOLD(
SOLDSEQ NUMBER(6) PRIMARY KEY,
CUSTOMERID VARCHAR2(30) CONSTRAINT SOLD_COL2_FK REFERENCES CUSTOMER(CUSTOMERID), 
PRODUCTSEQ NUMBER(6) CONSTRAINT SOLD_COL3_FK REFERENCES PRODUCT(PRODUCTSEQ), 
QUANTITY NUMBER(6),
INDATE DATE DEFAULT SYSDATE
);

CREATE TABLE ADMIN(
ADMINID VARCHAR2(30) primary key,
ADMINPW VARCHAR2(30)
);
 
CREATE SEQUENCE PRODUCTSEQ;
CREATE SEQUENCE SOLDSEQ;