	


https://www.erdcloud.com/d/ENsFuen4Jk7BLbCTk


		CREATE TABLE INGREDIENTS(
		INGREDIENTSEQ VARCHAR2(30) PRIMARY KEY,
		INGREDIENTNAME VARCHAR2(30),
		INGREDIENTCOMMENT VARCHAR2(1000)
		)
		
		CREATE TABLE RECIPES (
		RECIPESEQ VARCHAR2(30) PRIMARY KEY,
		DRINKNAME VARCHAR2(30) REFERENCES DRINKS (DRINKNAME),
		INGREDIENTSEQ VARCHAR2(30) REFERENCES INGREDIENTS (INGREDIENTSEQ),
		QUANTITY NUMBER,
		INDATE DATE
		)
		
		CREATE TABLE DRINKS(
		DRINKNAME VARCHAR2(30) PRIMARY KEY,
		DRINKCOMMENT VARCHAR2(1000),
		PRICE NUMBER,
		INDATE DATE
		)
		
		CREATE TABLE CUSTOMERS(
		CUSTOMERID VARCHAR2(30) PRIMARY KEY
		)
		
		CREATE TABLE SOLD (
		SOLDSEQ VARCHAR2(30) PRIMARY KEY,
		CUSTOMERID VARCHAR2(30)  REFERENCES CUSTOMERS (CUSTOMERID),
		DRINKNAME VARCHAR2(30)REFERENCES DRINKS (DRINKNAME),
		QUANTITY NUMBER
		)
		
		CREATE SEQUENCE SOLDSEQ
		CREATE SEQUENCE RECIPESEQ
		CREATE SEQUENCE INGREDIENTSEQ